# Generated by Django 2.2.5 on 2019-12-20 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='VehicleModel',
        ),
    ]
