# Generated by Django 2.2.5 on 2019-12-20 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20191220_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
