# Generated by Django 2.2.5 on 2019-12-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20191220_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
