# Generated by Django 2.2.5 on 2019-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='red', max_length=50),
            preserve_default=False,
        ),
    ]
