# Generated by Django 2.2.5 on 2019-12-22 19:28

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, upload_to=vehicle.models.user_directory_path),
        ),
    ]
