# Generated by Django 2.2.5 on 2019-12-22 19:43

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20191222_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.FileField(blank=True, upload_to=vehicle.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
